# Generated by Django 5.2.17 on 2026-09-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevidence',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
