# Generated by Django 5.2.17 on 2026-09-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_steam_library"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="sentiment",
            field=models.SmallIntegerField(
                choices=[
                    (2, "Loved"),
                    (1, "Like"),
                    (-1, "Dislike"),
                    (0, "Ignore"),
                    (-2, "Not played yet"),
                ]
            ),
        ),
    ]
