# Generated by Django 5.2.17 on 2026-10-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_dismissedsuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationrun",
            name="error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="recommendationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="done",
                max_length=9,
            ),
        ),
    ]
